// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZwD4F-jTPCIkWWyMMCgpF9zMUQ90vqXk',
    appId: '1:262681042121:web:379a9d9b9194d4cd6d0118',
    messagingSenderId: '262681042121',
    projectId: 'emsdirectaid',
    authDomain: 'emsdirectaid.firebaseapp.com',
    storageBucket: 'emsdirectaid.appspot.com',
    measurementId: 'G-R4TS1QLBS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalTTSJY-hArtu_Pv0_4TSynCQI0ffGCU',
    appId: '1:262681042121:android:5942fc9128561bc56d0118',
    messagingSenderId: '262681042121',
    projectId: 'emsdirectaid',
    storageBucket: 'emsdirectaid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYN9322WBkYoFGeQzdhj9xE9vMYr4tFE',
    appId: '1:262681042121:ios:6ea014b7a709bccb6d0118',
    messagingSenderId: '262681042121',
    projectId: 'emsdirectaid',
    storageBucket: 'emsdirectaid.appspot.com',
    iosBundleId: 'com.example.daid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYN9322WBkYoFGeQzdhj9xE9vMYr4tFE',
    appId: '1:262681042121:ios:6ea014b7a709bccb6d0118',
    messagingSenderId: '262681042121',
    projectId: 'emsdirectaid',
    storageBucket: 'emsdirectaid.appspot.com',
    iosBundleId: 'com.example.daid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZwD4F-jTPCIkWWyMMCgpF9zMUQ90vqXk',
    appId: '1:262681042121:web:84889fa3f2ebd5ea6d0118',
    messagingSenderId: '262681042121',
    projectId: 'emsdirectaid',
    authDomain: 'emsdirectaid.firebaseapp.com',
    storageBucket: 'emsdirectaid.appspot.com',
    measurementId: 'G-W34XS4DE35',
  );
}
